## numpy vectorization tutorial 

In [12]:
import numpy as np

In [19]:
a = np.array((1, 2, 3))
print(a)
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5

print(a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.shape)
print()
print(b[0,1], b[1, 0])

[1 2 3]
(3,)
1 2 3
[5 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)

2 4


In [28]:
a = np.zeros((2,2))
print(a)

b = np.ones((1,2))
print(b)

c = np.full((2,2), 7)
print(c)

d = np.eye(10)
print(d)

e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0.69575887 0.62616253]
 [0.95151945 0.2298216 ]]


In [32]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

b = a[:2, :3]

print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3]
 [5 6 7]]


In [13]:
np.arange(4)+1

array([1, 2, 3, 4])

In [9]:
from autograd import grad

def sample_func(x):
    return x**4 + x**2 + 10*x - 50

grad_x = grad(sample_func)

In [10]:
grad_x(1.0)

16.0